# Generated by Django 3.2.12 on 2023-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='description',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finch',
            name='habitat',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
