# Generated by Django 3.2.12 on 2023-09-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_sponsor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='sponsors',
            field=models.ManyToManyField(to='main_app.Sponsor'),
        ),
    ]
